#!/usr/bin/env python3
import os
import sys
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"
_SCRIPT = "silero_speech_prob.py"

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
os.execv(
    context.env_exe,
    [context.env_exe, str(_PROGRAM_DIR / "bin" / _SCRIPT)] + sys.argv[1:],
)
