#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# Base directory of repo
base_dir="$(realpath "${this_dir}/..")"

# Copy default config
config_dir="${base_dir}/config"
config_file="${config_dir}/configuration.yaml"

if [ ! -f "${config_file}" ]; then
    cp "${config_dir}/configuration.default.yaml" "${config_file}"
fi

# -----------------------------------------------------------------------------

echo "OK"
