#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# Base directory of repo
base_dir="$(realpath "${this_dir}/..")"

# Copy default config
config_dir="${base_dir}/config"

mkdir -p "${config_dir}"

# -----------------------------------------------------------------------------

echo "OK"
