#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# Base directory of repo
base_dir="$(realpath "${this_dir}/..")"

# Path to virtual environment
: "${venv:=${base_dir}/.venv}"

# Python binary to use
: "${PYTHON=python3}"

if [ -d "${venv}" ]; then
    source "${venv}/bin/activate"
fi

pip3 install -r "${base_dir}/requirements_http_api.txt"

# -----------------------------------------------------------------------------

echo "OK"
