#!/usr/bin/env bash
set -eo pipefail

# Directory of *this* script
this_dir="$( cd "$( dirname "$0" )" && pwd )"

# Base directory of repo
base_dir="$(realpath "${this_dir}/..")"

# Path to virtual environment
: "${venv:=${base_dir}/.venv}"

# Python binary to use
: "${PYTHON=python3}"

python_version="$(${PYTHON} --version)"

# Create virtual environment
echo "Creating virtual environment at ${venv} (${python_version})"
rm -rf "${venv}"
"${PYTHON}" -m venv "${venv}"
source "${venv}/bin/activate"

# Install Python dependencies
echo 'Installing Python dependencies'
pip3 install --upgrade pip
pip3 install --upgrade wheel setuptools

if [ -f "${base_dir}/requirements.txt" ]; then
    pip3 install -r "${base_dir}/requirements.txt"
fi

# Copy default config
config_dir="${base_dir}/config"
config_file="${config_dir}/configuration.yaml"

if [ ! -f "${config_file}" ]; then
    cp "${config_dir}/configuration.default.yaml" "${config_file}"
fi

# -----------------------------------------------------------------------------

echo "OK"
