#!/usr/bin/env python3
import os
import subprocess
import sys
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

context = venv.EnvBuilder().ensure_directories(_VENV_DIR)
subprocess.check_call(
    [os.path.join(context.bin_path, "tts"), "--list_models"] + sys.argv[1:]
)
